/**
 * 32 3PSPs.
 */
export enum ECompanyTradeMarks {
  AFAS = 'AFAS',
  BITVAVO = 'Bitvavo',
  BITWARDEN = 'Bitwarden',
  BLOCKRISE = 'Blockrise',
  BUNQ = 'Bunq',
  CHAINSTACK = 'Chainstack',
  CLOUDFLARE = 'Cloudflare',
  COLT = 'Colt',
  COINGECKO = 'CoinGecko',
  COMPLYADVANTAGE = 'ComplyAdvantage',
  ELLIPTIC = 'Elliptic',
  GITHUB = 'Github',
  GOOGLE = 'Google',
  IDIN = 'iDIN',
  KRAKEN = 'Kraken',
  LINEAR = 'Linear',
  MICROSOFT = 'Microsoft',
  NOTION = 'Notion',
  POSTCODEAPI = 'Postcode API',
  PAY_DOT = 'Pay.',
  SANITY = 'Sanity',
  SCRIVE = 'Scrive',
  SECUROSYS = 'Securosys',
  SENDGRID = 'Sendgrid',
  SENTRY = 'Sentry',
  SLACK = 'Slack',
  SONARCLOUD = 'SonarCloud',
  SUREPAY = 'SurePay',
  TWILIO = 'Twilio',
  UNIFI = 'Unifi',
  VERCEL = 'Vercel',
  VERIFF = 'Veriff',
}
