/**
 * 32 3PSPs.
 */
export enum ECompanyLegalNames {
  AFAS = 'Afas Software B.V.',
  BITVAVO = 'Bitvavo B.V.',
  BITWARDEN = 'Bitwarden Inc.',
  BLOCKRISE = 'Blockrise Capital B.V.',
  BUNQ = 'Bunq B.V.',
  CHAINSTACK = 'Chainstack Pte. Ltd.',
  CLOUDFLARE = 'Cloudflare Inc.',
  COLT = 'Colt Technology Services Europe Ltd.',
  COINGECKO = 'Gecko Labs Pte. Ltd.',
  COMPLYADVANTAGE = 'Compliance Advantage Ltd.',
  ELLIPTIC = 'Elliptic Enterprises Ltd.',
  GITHUB = 'Github Inc.',
  GOOGLE = 'Google LLC',
  IDIN = 'iDIN B.V.',
  KRAKEN = 'Payward Continental Services Limited',
  LINEAR = 'Linear Orbit Inc.',
  MICROSOFT = 'Microsoft Corporation',
  NOTION = 'Notion Labs Inc.',
  POSTCODEAPI = 'Postcode API B.V.',
  PAY_DOT = 'Tintel B.V.',
  SANITY = 'Sanity US, Inc.',
  SCRIVE = 'Scrive AB',
  SECUROSYS = 'Securosys SA',
  SENDGRID = 'Sendgrid Inc.',
  SENTRY = 'Functional Software Inc.',
  SLACK = 'Slack Technologies Inc.',
  SONARCLOUD = 'SonarSource SA',
  SUREPAY = 'SurePay B.V.',
  TWILIO = 'Twilio Inc.',
  UNIFI = 'Ubiquiti Inc.',
  VERCEL = 'Vercel Inc.',
  VERIFF = 'Veriff OÜ',
}
