const nxPreset = require('@nx/jest/preset').default;

module.exports = {
  ...nxPreset,
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['text'],
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/migrations/**/*',
    '!**/*.module.ts',
    '!**/main.ts',
    '!**/*.entity.ts',
    '!**/*.controller.ts',
    '!**/*.dto.ts',
    '!**/*models/*.model.ts',
    '!**/*.constraint.ts',
    '!**/*.constants.ts',
    '!**/*.config.(t|j)s',
    '!**/*.decorator.ts',
    '!**/*.interface.ts',
    '!**/guards/*',
    '!**/*.interceptor.ts',
    '!**/common/constants/sentry/*',
    '!**/*xml*.ts',
    '!**/*.enum.ts',
    '!**/tests/**/*.ts',
    '!**/typeorm/decorators/**/*.ts',
    '!**/proxies/(auth|blockrise-api)/**/(endpoints|interfaces)/**/*.ts',
    '!**/invoice-document.service.ts',
    '!**/gcloud/storage.service.ts',
    '!**/prisma.service.ts',
    '!**/prisma/**/*.ts',
    '!**/test/**/*.ts',
    '!**/interfaces/**/*',
    '!**/enums/**/*',
    '!**/endpoints/**/*',
    '!**/index.ts',
    '!**/*.repository.ts',
    '!**/transaction.template.ts',
  ],
  testPathIgnorePatterns: ['/*old/'],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 100,
      statements: -10,
    },
  },
};
