import { ECompanies } from '../enums/companies.enum';
import { Countries } from '../enums/countries.enum';

export const COMPANY_COUNTRY_CODES: Record<ECompanies, Countries> = {
  [ECompanies.AFAS]: Countries.NL,
  [ECompanies.BITVAVO]: Countries.NL,
  [ECompanies.BITWARDEN]: Countries.US,
  [ECompanies.BLOCKRISE]: Countries.NL,
  [ECompanies.BUNQ]: Countries.NL,
  [ECompanies.CHAINSTACK]: Countries.SG,
  [ECompanies.CLOUDFLARE]: Countries.US,
  [ECompanies.COLT]: Countries.GB,
  [ECompanies.COINGECKO]: Countries.SG,
  [ECompanies.COMPLYADVANTAGE]: Countries.GB,
  [ECompanies.ELLIPTIC]: Countries.GB,
  [ECompanies.GITHUB]: Countries.US,
  [ECompanies.GOOGLE]: Countries.US,
  [ECompanies.IDIN]: Countries.NL,
  [ECompanies.KRAKEN]: Countries.IE,
  [ECompanies.LINEAR]: Countries.US,
  [ECompanies.MICROSOFT]: Countries.US,
  [ECompanies.NOTION]: Countries.US,
  [ECompanies.POSTCODEAPI]: Countries.NL,
  [ECompanies.PAY_DOT]: Countries.NL,
  [ECompanies.SANITY]: Countries.US,
  [ECompanies.SCRIVE]: Countries.SE,
  [ECompanies.SECUROSYS]: Countries.CH,
  [ECompanies.SENDGRID]: Countries.US,
  [ECompanies.SENTRY]: Countries.US,
  [ECompanies.SLACK]: Countries.US,
  [ECompanies.SONARCLOUD]: Countries.CH,
  [ECompanies.SUREPAY]: Countries.NL,
  [ECompanies.TWILIO]: Countries.US,
  [ECompanies.UNIFI]: Countries.US,
  [ECompanies.VERCEL]: Countries.US,
  [ECompanies.VERIFF]: Countries.EE,
};
