import { ECompanies } from '../../common/companies.enum';
import { Countries } from '../../common/countries.enum';

export const COMPANY_COUNTRY_CODES: Record<ECompanies, Countries> = {
  [ECompanies.ALPHABET]: Countries.US,
  [ECompanies.BITVAVO]: Countries.NL,
  [ECompanies.BITWARDEN]: Countries.US,
  [ECompanies.BLUEM]: Countries.NL,
  [ECompanies.BLOCKRISE]: Countries.NL,
  [ECompanies.BLOCKRISE_GROUP]: Countries.NL,
  [ECompanies.STICHTING_BLOCKRISE]: Countries.NL,
  [ECompanies.BUNQ]: Countries.NL,
  [ECompanies.CHAINSTACK]: Countries.SG,
  [ECompanies.COLT]: Countries.GB,
  [ECompanies.COMPLYADVANTAGE]: Countries.GB,
  [ECompanies.ELLIPTIC]: Countries.GB,
  [ECompanies.EXPO]: Countries.US,
  [ECompanies.FLANTUA]: Countries.NL,
  [ECompanies.GITHUB]: Countries.US,
  [ECompanies.GOOGLE_IRELAND]: Countries.IE,
  [ECompanies.HEXNODE]: Countries.US,
  [ECompanies.KRAKEN]: Countries.IE,
  [ECompanies.LINEAR]: Countries.US,
  [ECompanies.MICROSOFT]: Countries.US,
  [ECompanies.MICROSOFT_IRELAND]: Countries.IE,
  [ECompanies.NOTION]: Countries.US,
  [ECompanies.PAY_DOT]: Countries.NL,
  [ECompanies.POSTCODEDOTNL]: Countries.NL,
  [ECompanies.SANITY]: Countries.US,
  [ECompanies.SCRIVE]: Countries.SE,
  [ECompanies.SECUROSYS]: Countries.CH,
  [ECompanies.SENDGRID]: Countries.US,
  [ECompanies.SENTRY]: Countries.US,
  [ECompanies.SLACK]: Countries.US,
  [ECompanies.SONARCLOUD]: Countries.CH,
  [ECompanies.TWILIO]: Countries.US,
  [ECompanies.UBIQUITI]: Countries.US,
  [ECompanies.UNISCAPE]: Countries.NL,
  [ECompanies.VERCEL]: Countries.US,
  [ECompanies.VERIFF]: Countries.EE,
  [ECompanies.ZENDESK]: Countries.US,

  /**
   * Discarded
   */
  [ECompanies.BLOCKCHAINDOTCOM]: Countries.GB,
  [ECompanies.COINGECKO]: Countries.SG,
  [ECompanies.GLASSNODE]: Countries.CH,
  [ECompanies.GRAFANA]: Countries.GB,
  [ECompanies.ING]: Countries.NL,
  [ECompanies.KWINZO]: Countries.NL,
  [ECompanies.MEMPOOL]: Countries.JP,
  [ECompanies.NEXTNOVATE]: Countries.NL,
  [ECompanies.QUICKNODE]: Countries.US,
  [ECompanies.SHIFTBASE]: Countries.NL,
};
