export enum ECompanies {
  /**
   * Blockrise
   */
  BLOCKRISE = 'BLOCKRISE',
  BLOCKRISE_GROUP = 'BLOCKRISE_GROUP',
  STICHTING_BLOCKRISE = 'STICHTING_BLOCKRISE',

  /**
   * Critical
   */
  BUNQ = 'BUNQ',
  COMPLYADVANTAGE = 'COMPLYADVANTAGE',
  ELLIPTIC = 'ELLIPTIC',
  GOOGLE_IRELAND = 'GOOGLE_IRELAND',
  MICROSOFT_IRELAND = 'MICROSOFT_IRELAND',
  SECUROSYS = 'SECUROSYS',


  /**
   * Non-Critical
   */
  AFAS = 'AFAS',
  ALPHABET = 'ALPHABET',
  BITVAVO = 'BITVAVO',
  BITWARDEN = 'BITWARDEN',
  BLOCKCHAINDOTCOM = 'BLOCKCHAINDOTCOM',
  CHAINSTACK = 'CHAINSTACK',
  COINGECKO = 'COINGECKO',
  COLT = 'COLT',
  EXPO = 'EXPO',
  GITHUB = 'GITHUB',
  GLASSNODE = 'GLASSNODE', // Only used by Corporate for chart analysis
  GRAFANA = 'GRAFANA',
  GOOGLE = 'GOOGLE', // Google Cloud ?
  HEXNODE = 'HEXNODE',
  IDIN = 'IDIN', // Bluem
  ING = 'ING',
  KRAKEN = 'KRAKEN',
  KWINZO = 'KWINZO',
  LINEAR = 'LINEAR',
  MEMPOOL = 'MEMPOOL',
  MICROSOFT = 'MICROSOFT',
  NEXTNOVATE = 'NEXTNOVATE', // Only as "Betaalconstructie" for payment to Google Cloud. If Nextnovate falls out then we can still pay directly to Google.
  NOTION = 'NOTION',
  POSTCODEDOTNL = 'POSTCODEDOTNL',
  PAY_DOT = 'PAY_DOT',
  QUICKNODE = 'QUICKNODE',
  SANITY = 'SANITY',
  SCRIVE = 'SCRIVE',
  SENDGRID = 'SENDGRID',
  SENTRY = 'SENTRY',
  SHIFTBASE = 'SHIFTBASE',
  SLACK = 'SLACK',
  SONARCLOUD = 'SONARCLOUD',
  SUREPAY = 'SUREPAY', // Bluem
  TWILIO = 'TWILIO',
  UBIQUITI = 'UBIQUITI', // Unifi
  UNISCAPE = 'UNISCAPE',
  VERCEL = 'VERCEL',
  VERIFF = 'VERIFF',
  ZENDESK = 'ZENDESK',
}
