export enum ECompanies {
  /**
   * Blockrise
   */
  BLOCKRISE = 'BLOCKRISE',
  BLOCKRISE_GROUP = 'BLOCKRISE_GROUP',
  STICHTING_BLOCKRISE = 'STICHTING_BLOCKRISE',

  /**
   * Critical (6)
   */
  BUNQ = 'BUNQ',
  COMPLYADVANTAGE = 'COMPLYADVANTAGE',
  ELLIPTIC = 'ELLIPTIC',
  GOOGLE_IRELAND = 'GOOGLE_IRELAND',
  MICROSOFT_IRELAND = 'MICROSOFT_IRELAND',
  SECUROSYS = 'SECUROSYS',


  /**
   * Non-Critical (26)
   */
  BITVAVO = 'BITVAVO',
  BITWARDEN = 'BITWARDEN',
  BLUEM = 'BLUEM',
  CHAINSTACK = 'CHAINSTACK',
  COLT = 'COLT',
  EXPO = 'EXPO',
  FLANTUA = 'FLANTUA',
  GITHUB = 'GITHUB',
  HEXNODE = 'HEXNODE',
  KRAKEN = 'KRAKEN',
  LINEAR = 'LINEAR',
  NOTION = 'NOTION',
  POSTCODEDOTNL = 'POSTCODEDOTNL',
  PAY_DOT = 'PAY_DOT',
  SANITY = 'SANITY',
  SCRIVE = 'SCRIVE',
  SENDGRID = 'SENDGRID',
  SENTRY = 'SENTRY',
  SLACK = 'SLACK',
  SONARCLOUD = 'SONARCLOUD',
  TWILIO = 'TWILIO',
  UBIQUITI = 'UBIQUITI',
  UNISCAPE = 'UNISCAPE',
  VERCEL = 'VERCEL',
  VERIFF = 'VERIFF',
  ZENDESK = 'ZENDESK',

  /**
   * OTHER
   */
  ALPHABET = 'ALPHABET', // Google parent
  MICROSOFT = 'MICROSOFT', // Microsoft parent

  /**
   * DISCARDED
   */
  BLOCKCHAINDOTCOM = 'BLOCKCHAINDOTCOM',
  COINGECKO = 'COINGECKO',
  GLASSNODE = 'GLASSNODE', // Only used by Corporate for chart analysis
  GRAFANA = 'GRAFANA',
  ING = 'ING',
  KWINZO = 'KWINZO',
  MEMPOOL = 'MEMPOOL',
  NEXTNOVATE = 'NEXTNOVATE', // Only as "Betaalconstructie" for payment to Google Cloud. If Nextnovate falls out then we can still pay directly to Google.
  QUICKNODE = 'QUICKNODE',
  SHIFTBASE = 'SHIFTBASE',
}
