export enum EContracts {
  /**
   * CRITICAL (7)
   */
  BUNQ_BLOCKRISE_BV = 'CONTRACT_1',
  BUNQ_BLOCKRISE_STICHTING = 'CONTRACT_2',
  COMPLYADVANTAGE = 'CONTRACT_3',
  ELLIPTIC = 'CONTRACT_4',
  GOOGLE_IRELAND = 'CONTRACT_5',
  MICROSOFT_IRELAND = 'CONTRACT_6',
  SECUROSYS = 'CONTRACT_7',
  /**
   * NON-CRITICAL (27)
   */
  AFAS = 'CONTRACT_8',
  BITVAVO = 'CONTRACT_9',
  BITWARDEN = 'CONTRACT_10',
  CHAINSTACK = 'CONTRACT_11',
  COLT = 'CONTRACT_12',
  EXPO = 'CONTRACT_13',
  GITHUB = 'CONTRACT_14',
  HEXNODE = 'CONTRACT_15',
  IDIN = 'CONTRACT_16',
  KRAKEN = 'CONTRACT_17',
  LINEAR = 'CONTRACT_18',
  NOTION = 'CONTRACT_19',
  PAY_DOT = 'CONTRACT_20',
  POSTCODEDOTNL = 'CONTRACT_21',
  SANITY = 'CONTRACT_22',
  SCRIVE = 'CONTRACT_23',
  SENDGRID = 'CONTRACT_24',
  SENTRY = 'CONTRACT_25',
  SLACK = 'CONTRACT_26',
  SONARCLOUD = 'CONTRACT_27',
  SUREPAY = 'CONTRACT_28',
  TWILIO = 'CONTRACT_29',
  UBIQUITI = 'CONTRACT_30',
  UNISCAPE = 'CONTRACT_31',
  VERCEL = 'CONTRACT_32',
  VERIFF = 'CONTRACT_33',
  ZENDESK = 'CONTRACT_34',
}
