import { ECompanies } from '../../enums/companies.enum';

const _COMPANY_TRADEMARKS = {
  [ECompanies.AFAS]: 'AFAS',
  [ECompanies.BITVAVO]: 'Bitvavo',
  [ECompanies.BITWARDEN]: 'Bitwarden',
  [ECompanies.BLOCKCHAINDOTCOM]: 'Blockchain',
  [ECompanies.BLOCKRISE]: 'Blockrise',
  [ECompanies.STICHTING_BLOCKRISE]: 'Stichting Blockrise',
  [ECompanies.BUNQ]: 'Bunq',
  [ECompanies.CHAINSTACK]: 'Chainstack',
  [ECompanies.CLOUDFLARE]: 'Cloudflare',
  [ECompanies.COLT]: 'Colt',
  [ECompanies.COINGECKO]: 'CoinGecko',
  [ECompanies.COMPLYADVANTAGE]: 'ComplyAdvantage',
  [ECompanies.ELLIPTIC]: 'Elliptic',
  [ECompanies.GITHUB]: 'Github',
  [ECompanies.GLASSNODE]: 'Glassnode',
  [ECompanies.GOOGLE]: 'Google',
  [ECompanies.GRAFANA]: 'Grafana',
  [ECompanies.HEXNODE]: 'HexNode',
  [ECompanies.IDIN]: 'iDIN',
  [ECompanies.ING]: 'ING',
  [ECompanies.KRAKEN]: 'Kraken',
  [ECompanies.KWINZO]: 'Kwinzo',
  [ECompanies.LINEAR]: 'Linear',
  [ECompanies.MEMPOOL]: 'Mempool',
  [ECompanies.MICROSOFT]: 'Microsoft',
  [ECompanies.NEXTNOVATE]: 'Nextnovate',
  [ECompanies.NOTION]: 'Notion',
  [ECompanies.POSTCODEAPI]: 'Postcode API',
  [ECompanies.PAY_DOT]: 'Pay.',
  [ECompanies.QUICKNODE]: 'QuickNode',
  [ECompanies.SANITY]: 'Sanity',
  [ECompanies.SCRIVE]: 'Scrive',
  [ECompanies.SECUROSYS]: 'Securosys',
  [ECompanies.SENDGRID]: 'Sendgrid',
  [ECompanies.SENTRY]: 'Sentry',
  [ECompanies.SHIFTBASE]: 'Shiftbase',
  [ECompanies.SLACK]: 'Slack',
  [ECompanies.SONARCLOUD]: 'SonarCloud',
  [ECompanies.SUREPAY]: 'SurePay',
  [ECompanies.TWILIO]: 'Twilio',
  [ECompanies.UBIQUITI]: 'Ubiquiti',
  [ECompanies.UNISCAPE]: 'Uniscape',
  [ECompanies.VERCEL]: 'Vercel',
  [ECompanies.VERIFF]: 'Veriff',
  [ECompanies.ZENDESK]: 'Zendesk',
} as const;
export const COMPANY_TRADEMARKS: Record<ECompanies, typeof _COMPANY_TRADEMARKS[ECompanies]> = _COMPANY_TRADEMARKS;
